SELECT
    U.USERNAME_ KULLANICI_ADI,
    U.NAMESURNAME AD_SOYAD,
    U.TELNR1 TELEFON_NUMARASI,
    U.TELNR2,    
    C.COUNTRY ULKE,
    CT.CITY SEHIR,
    T.TOWN ILCE,
    A.ADDRESSTEXT ADRES,
    O.ID SIPARIS_ID,
    ITM.ITEMCODE URUN_KODU,
    ITM.ITEMNAME URUN_ADI,
    ITM.BRAND MARKA,
	ITM.CATEGORY1 KATEGORI1,
    ITM.CATEGORY2 KATEGORI2,
    ITM.CATEGORY3 KATEGORI3,
    ITM.CATEGORY4 KATEGORI4,
    OD.AMOUNT MIKTAR,
    OD.UNITPRICE BIRIM_FIYAT,
    OD.LINETOTAL TOPLAM_TUTAR,
    CONVERT(DATE, O.DATE_) AS TARIH,
    CONVERT(TIME, O.DATE_) AS SAAT,
    DATEPART(YEAR, O.DATE_) YIL,
    DBO.AY_ADI(O.DATE_) AY,
    DBO.GUN(O.DATE_) GUN
FROM
    ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
WHERE O.DATE_ BETWEEN '2019-01-01' AND '2019-01-31';

